Use `offsetof` instead of custom implementation
Newer standards compliant approach also works on 64-bit target
platforms. Old code fails with (one of many instances):

```
g++ -std=c++0x -DNO_OOP_MACROS -DDEBUG -D__LPC11XX__ -DIAP_EMULATION -I"XXX\software-arm-lib\sblib\inc" -I"XXX\software-arm-lib\test\sblib\cpu-emu" -I"XXX\software-arm-lib\Catch\inc" -I"XXX\software-arm-lib\test\sblib\inc" -O0 -g3 -Wall -m64 -c -fmessage-length=0 -MMD -MP -MF"sblib/lpc11xx/platform.d" -MT"sblib/lpc11xx/platform.o" -o "sblib/lpc11xx/platform.o" "C:/Users/Thomas/Documents/Source/software-arm-lib/sblib/src/lpc11xx/platform.cpp"
In file included from XXX\software-arm-lib\sblib\inc/sblib/interrupt.h:15,
                 from XXX\software-arm-lib\sblib\inc/sblib/core.h:17,
                 from C:/Users/Thomas/Documents/Source/software-arm-lib/sblib/src/lpc11xx/platform.cpp:12:
XXX\software-arm-lib\sblib\inc/sblib/utils.h:74:34: error: cast from 'volatile uint32_t*' {aka 'volatile unsigned int*'} to 'unsigned int' loses precision [-fpermissive]
   74 | #define OFFSET_OF(type, field)  ((unsigned int) &(((type *) 0)->field))
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Thomas/Documents/Source/software-arm-lib/sblib/src/lpc11xx/platform.cpp:19:32: note: in expansion of macro 'OFFSET_OF'
   19 | #define OFFSET_OF_IOCON(pin)  (OFFSET_OF(LPC_IOCON_TypeDef, pin) >> 2)
      |                                ^~~~~~~~~
C:/Users/Thomas/Documents/Source/software-arm-lib/sblib/src/lpc11xx/platform.cpp:25:9: note: in expansion of macro 'OFFSET_OF_IOCON'
   25 |         OFFSET_OF_IOCON(RESET_PIO0_0),
      |         ^~~~~~~~~~~~~~~
```