Fix "error: expected primary-expression before 'volatile'"
With GCC 12.2 64-bit on Windows, compilation of protocol.cpp fails with
below error message. Root cause is that <sblib/internal/iap.h> via some
other includes indirectly defines `__I` as `volatile`, a key word. Then
there is protocol.h, which includes Catch.hpp, which causes inclusion of
xmmintrin.h, which defines function `_mm_setcsr (unsigned int __I)`.
Due to the preprocessor, the function does not have a parameter name
anymore and thus compilation fails.

Workaround this by putting the protocol.h include first.

```
g++ -std=c++0x -DNO_OOP_MACROS -DDEBUG -D__LPC11XX__ -DIAP_EMULATION -I"XXX\software-arm-lib\sblib\inc" -I"XXX\software-arm-lib\test\sblib\cpu-emu" -I"XXX\software-arm-lib\Catch\inc" -I"XXX\software-arm-lib\test\sblib\inc" -O0 -g3 -Wall -m32 -c -fmessage-length=0 -MMD -MP -MF"src/protocol.d" -MT"src/protocol.o" -o "src/protocol.o" "../src/protocol.cpp"
In file included from XXX\software-arm-lib\test\sblib\cpu-emu/LPC11xx.h:118,
                 from XXX\software-arm-lib\sblib\inc/sblib/platform.h:14,
                 from XXX\software-arm-lib\sblib\inc/sblib/internal/iap.h:12,
                 from ../src/protocol.cpp:12:
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/xmmintrin.h: In function 'void _mm_setcsr(unsigned int)':
XXX\software-arm-lib\test\sblib\cpu-emu/core_cm0.h:163:21: error: expected primary-expression before 'volatile'
  163 |   #define   __I     volatile             /*!< Defines 'read only' permissions                 */
      |                     ^~~~~~~~
```